---
- hosts: 172.31.6.127
  become: yes 
  tasks: 
  - include: myfile.yml

  - name: install web server
    apt:
      name: apache2

  - name: i want to copy static file into ansible
    copy:
       src: staticfile.txt
       dest: /home/ubuntu/staticfile.txt  
 
  - name: i wnat to copy dyna file into ansible nodes     
    template:
       src: mydynofile.j2
       dest: /var/www/html/index.html

  - name: i want to download remote file into ansible node
    get_url:
       url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.87/bin/apache-tomcat-8.5.87.exe
       dest: /home/ubuntu/https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.87/bin/apache-tomcat-8.5.87.exe
    force_basic_auth: yes     