---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{x}}"
      state: present
    when: ansible_os_family =="Debian"     
          
  - name: install java on RedHat
    yum:
      name: "{{y}}"
      state: present
    when: ansible_os_family =="RedHat"






