---
- hosts: 172.31.6.127
  become: yes 
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: x
    

  - name: i want display my fisrt tasks result
    debug:
         msg: "{{x}}" 

  - name: install git 
    apt: 
       name: git 
       state: present
    whene: x.stderr ==""

  - name: install tree
    apt:
       name: tree
       state: present
    when: x.stderr !=""          