---
- hosts: 172.31.6.127
  become: yes
  tasks: 
  - name: install git 
    apt:
       name: git
       state: present

  - name: install tree
    apt:
      name: tree
      stateddd: present
    ignore_errors: yes

  - name: install wget
    apt: 
      name:
      state: present