---
- hosts: 172.31.6.127
  become: yes 
  tasks: 
  - name: install wget
    apt:
          name: wget
          state: present
    tags: mywget   
  
  - name: insatll tree
    apt: 
          name: tree
          state: present
    tags: mytree

  - name: install git 
    apt:
           name: git 
           state: present
    tags: mygit      
           