---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    apt:
       name: apache2
       state: present
    when: anible_os_family =="Debian"  


  - name: i want to start myWebServer
    service:
       name: apache2
       state: started
    when: anible_os_family =="Debian"   