---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    apt:
       name: "{{mywebvarubuntu}}"
       state: present
    when: ansible_os_family =="Debian"  


  - name: i want to start myWebServer on ubuntu
    service:
       name: "{{mywebvarubuntu}}"
       state: started
    when: ansible_os_family =="Debian"   


  - name: i want to install webserver on RedHat
    yum:
       name: "{{mywebvarredhat}}"
       state: present
    when: ansible_os_family =="RedHat"  


  - name: i want to start myWebServer on RedHat
    service:
       name: "{{mywebvarredhat}}"
       state: started
    when: ansible_os_family =="RedHat"   